In [75]:
import pandas as pd

In [86]:
ZomatoData = pd.read_csv('zomato.csv',encoding = 'unicode_escape')
ZomatoData = ZomatoData.drop_duplicates().reset_index(drop=True)
ZomatoData['City']= ZomatoData['City'].apply(lambda s:s.lower() if type(s) == str else s)
ZomatoData['Cuisines']= ZomatoData['Cuisines'].apply(lambda s:s.lower() if type(s) == str else s)
ZomatoData['City'] = ZomatoData['City'].apply(lambda s:'nashik' if s=='nasik' else s)
ZomatoData['Price_Range'] = ZomatoData['Average Cost for two'].apply(lambda x: 'low' if x<300 else ('mid' if 300<=x<700 else 'high'))

In [87]:
ZomatoData['Price_Range'].value_counts()

mid     4797
high    2658
low     1896
Name: Price_Range, dtype: int64

In [105]:
price='211'
if price not in ['high','mid','low'] and price.isnumeric():
    price=int(price)
    if price <300:price='low'
    elif price>700:price='high'
    else: price='medium'
        
price

'low'

In [127]:
data = ZomatoData.loc[(ZomatoData['City']=='new delhi') & (ZomatoData['Price_Range']=='low') & (ZomatoData['Cuisines'].str.contains('chinese')),['Restaurant Name','Address','Aggregate rating']].sort_values(by='Aggregate rating',ascending=False).head(5)

In [131]:
data.values.tolist()

[['Panchwati Rasoi', 'LSC, Savita Vihar Market, Anand Vihar, New Delhi', 3.8],
 ['Manohar Bikkaneri', '1512, Clock Tower, Near, Kamla Nagar, New Delhi', 3.8],
 ['Suresh Fast Food',
  '5, DDA Market, Hudson Lane, Kingsway Camp, Delhi University-GTB Nagar, New Delhi',
  3.7],
 ['Manohar Bikkaneri',
  '2, UA, Jawahar Nagar, Near Malkaganj Chowk, Kamla Nagar, New Delhi',
  3.6],
 ['Gaurav Pastry Palace', 'G-20/224-225, Rohini, New Delhi', 3.6]]

In [115]:
ZomatoData.loc[ZomatoData['Cuisines'].str.contains('north indian'),:]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Price_Range
0,3400025,Jahanpanah,1,agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",78.011544,27.161661,"north indian, mughlai",...,0,0,0,0,3,3.9,9ACD32,Good,140,high
1,3400341,Rangrezz Restaurant,1,agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,"Agra Cantt, Agra",0.000000,0.000000,"north indian, mughlai",...,0,0,0,0,2,3.5,9ACD32,Good,71,high
2,3400005,Time2Eat - Mama Chicken,1,agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,"Agra Cantt, Agra",78.011608,27.160832,north indian,...,0,0,0,0,2,3.6,9ACD32,Good,94,mid
3,3400005,Mama Chicken Mama Franky House,1,agra,"A-17, Shoping Arcade, Sadar Bazaar, Agra Cantt...",Agra Cantt,"Agra Cantt, Agra",78.011627,27.161854,"north indian, mughlai, rolls, chinese, fast fo...",...,0,1,0,0,2,4.3,5BA829,Very Good,31399,mid
5,3400017,Pinch Of Spice,1,agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,"Civil Lines, Agra",78.007625,27.201735,"north indian, chinese, mughlai",...,0,1,0,0,4,4.5,3F7E00,Excellent,6037,high
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9343,2800868,Raju's Kitchen,1,vizag,"D.no: 55-8-34/16, Ground Floor, APSEB Colony R...",Seethammadhara,"Seethammadhara, Vizag",83.314348,17.743710,"biryani, chinese, north indian, fast food, sou...",...,0,1,0,0,2,4.1,5BA829,Very Good,22124,mid
9344,2800418,Kaloreez,1,vizag,"Plot 95, Opposite St. Lukes Nursing School, Da...",Siripuram,"Siripuram, Vizag",0.000000,0.000000,"cafe, north indian, chinese",...,0,0,0,0,2,3.7,9ACD32,Good,85,mid
9345,2800856,Barbeque Nation,1,vizag,"Door 7-8-10, Pandurangapuram, Siripuram, Vizag",Siripuram,"Siripuram, Vizag",83.318533,17.717417,"mediterranean, north indian, south indian, keb...",...,1,1,0,0,3,4.0,5BA829,Very Good,1277,high
9347,2800042,Vista - The Park,1,vizag,"The Park, Beach Road, Pedda Waltair, Lawsons B...","The Park, Lawsons Bay","The Park, Lawsons Bay, Vizag",83.336840,17.721182,"american, north indian, thai, continental",...,0,0,0,0,4,3.8,9ACD32,Good,74,high
9349,2800901,Paradise Biryani,1,vizag,"9-14-4, VIP Road, CBM Compound, Sector 4, Siri...",Waltair Uplands,"Waltair Uplands, Vizag",83.316185,17.726766,"biryani, north indian, chinese, mughlai",...,0,1,0,0,3,4.0,5BA829,Very Good,17830,high

In [74]:
ZomatoData.City.unique()

array(['agra', 'ahmedabad', 'allahabad', 'amritsar', 'aurangabad',
       'bangalore', 'bhopal', 'bhubaneshwar', 'chandigarh', 'chennai',
       'coimbatore', 'dehradun', 'faridabad', 'gangtok', 'ghaziabad',
       'goa', 'gurgaon', 'guwahati', 'hyderabad', 'indore', 'jaipur',
       'kanpur', 'kochi', 'kolkata', 'lucknow', 'ludhiana', 'mangalore',
       'mohali', 'mumbai', 'mysore', 'nagpur', 'nashik', 'new delhi',
       'noida', 'ooty', 'panchkula', 'patna', 'puducherry', 'pune',
       'ranchi', 'secunderabad', 'shimla', 'surat', 'vadodara',
       'varanasi', 'vizag'], dtype=object)

In [15]:
WeOperate = ['New Delhi', 'Gurgaon', 'Noida', 'Faridabad', 'Allahabad', 'Bhubaneshwar', 'Mangalore', 'Mumbai', 'Ranchi', 'Patna', 'Mysore', 'Aurangabad', 'Amritsar', 'Puducherry', 'Varanasi', 'Nagpur', 'Vadodara', 'Dehradun', 'Vizag', 'Agra', 'Ludhiana', 'Kanpur', 'Lucknow', 'Surat', 'Kochi', 'Indore', 'Ahmedabad', 'Coimbatore', 'Chennai', 'Guwahati', 'Jaipur', 'Hyderabad', 'Bangalore', 'Nashik', 'Pune', 'Kolkata', 'Bhopal', 'Goa', 'Chandigarh', 'Ghaziabad', 'Ooty', 'Gangtok', 'Shimla']

In [32]:
WeOperate

['New Delhi',
 'Gurgaon',
 'Noida',
 'Faridabad',
 'Allahabad',
 'Bhubaneshwar',
 'Mangalore',
 'Mumbai',
 'Ranchi',
 'Patna',
 'Mysore',
 'Aurangabad',
 'Amritsar',
 'Puducherry',
 'Varanasi',
 'Nagpur',
 'Vadodara',
 'Dehradun',
 'Vizag',
 'Agra',
 'Ludhiana',
 'Kanpur',
 'Lucknow',
 'Surat',
 'Kochi',
 'Indore',
 'Ahmedabad',
 'Coimbatore',
 'Chennai',
 'Guwahati',
 'Jaipur',
 'Hyderabad',
 'Bangalore',
 'Nashik',
 'Pune',
 'Kolkata',
 'Bhopal',
 'Goa',
 'Chandigarh',
 'Ghaziabad',
 'Ooty',
 'Gangtok',
 'Shimla']

In [18]:
we = list(map(str.lower,WeOperate))

city for city in list(ZomatoData.City.unique()) if city not in we]

In [39]:
filter(lambda x: x if x not in we,ZomatoData.City.unique())

SyntaxError: invalid syntax (<ipython-input-39-fb1c4159e635>, line 1)

In [67]:
x=[]
for city in list(ZomatoData.City.unique()):
    if city not in we:
        x.append(city)
x

['mohali', 'nasik', 'panchkula', 'secunderabad']

In [42]:
ZomatoData.loc[ZomatoData.City.isin(x),:]

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
2273,123789,amigo's cafe,1,mohali,"bay shop 136, phase 3, mohali","phase 3b2 market, phase 3 mohali","phase 3b2 market, phase 3 mohali, mohali",76.721720,30.710284,"cafe, italian, fast food, beverages, desserts",...,indian rupees(rs.),1,1,0,0,2,4.3,5ba829,very good,12886
2274,120154,katani dhaba,1,mohali,"scf 40, b2, phase 3, mohali","phase 3b2 market, phase 3 mohali","phase 3b2 market, phase 3 mohali, mohali",76.719791,30.711665,"north indian, chinese",...,indian rupees(rs.),0,1,1,0,1,4.2,5ba829,very good,39648
2275,123013,amrit sweets,1,mohali,"scf 78, phase 5, mohali",phase 5,"phase 5, mohali",76.717836,30.714518,"mithai, north indian, south indian, street foo...",...,indian rupees(rs.),0,1,1,0,2,4.1,5ba829,very good,45512
2276,120160,khalsa dhaba,1,mohali,"scf 81, phase 5, mohali",phase 5,"phase 5, mohali",76.718125,30.714471,"north indian, chinese, desserts",...,indian rupees(rs.),0,1,1,0,2,4.2,5ba829,very good,30305
2277,124184,pizza freakerz,1,mohali,"booth 12, sector 67, mohali",sector 67,"sector 67, mohali",76.724717,30.680341,"pizza, fast food",...,indian rupees(rs.),0,1,0,0,2,4.3,5ba829,very good,29560
2278,18424018,the shooters cafe,1,mohali,"sco 654,himalaya marg road, sector 70, mohali,...",sector 70,"sector 70, mohali",76.718789,30.695551,"continental, north indian",...,indian rupees(rs.),0,1,0,0,2,4.3,5ba829,very good,99
2434,1600099,kokni darbar,1,nasik,"house 1326, damodar road, behind rajjak manzil...",doodh bazar,"doodh bazar, nasik",73.789741,19.998755,"fast food, chinese, mughlai, maharashtrian, no...",...,indian rupees(rs.),0,1,0,0,3,4.1,5ba829,very good,5041
2435,18839989,samarth juice center,1,nasik,"pethe high school compound, raviwar karanja, r...",ravivar nagar,"ravivar nagar, nasik",73.788798,20.006121,"beverages, juices",...,indian rupees(rs.),0,1,0,0,1,4.5,3f7e00,excellent,1686
9017,18609823,falcon cafe lounge,1,panchkula,"site 5, sector 16, panchkula",sector 16,"sector 16, panchkula",76.838678,30.695606,"cafe, north indian, chinese, fast food, beverages",...,indian rupees(rs.),1,1,1,0,3,4.4,5ba829,very good,6459
9018,120519,hops n grains,1,panchkula,"sco 358, sector 9, panchkula",sector 9,"sector 9, panchkula",76.849258,30.697859,"north indian, middle eastern, pizza",...,indian rupees(rs.),0,0,0,0,4,4.2,5ba829,very good,843
9174,96814,saffron mantra,1,secunderabad,"the purple leaf hotel, karkhana, secunderabad",karkhana,"karkhana, secunderabad",78.500366,17.458998,"north indian, chinese",...,indian rupees(rs.),1,1,0,0,2,4.4,5ba829,very good,494
9175,90499,coffee cup,1,secunderabad,"e 89, 1st floor, near canara bank, sainikpuri,...",sainikpuri,"sainikpuri, secunderabad",78.552126,17.483157,"cafe, continental, italian",...,indian rupees(rs.),1,1,1,0,2,4.5,3f7e00,excellent,18097

In [120]:
ZomatoData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9351 entries, 0 to 9350
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9351 non-null   int64
 1   Restaurant Name       9351 non-null   object
 2   Country Code          9351 non-null   int64
 3   City                  9351 non-null   object
 4   Address               9351 non-null   object
 5   Locality              9351 non-null   object
 6   Locality Verbose      9351 non-null   object
 7   Longitude             9351 non-null   float64
 8   Latitude              9351 non-null   float64
 9   Cuisines              9351 non-null   object
 10  Average Cost for two  9351 non-null   int64
 11  Currency              9351 non-null   object
 12  Has Table booking     9351 non-null   int64
 13  Has Online delivery   9351 non-null   int64
 14  Is delivering now     9351 non-null   int64
 15  Switch to order menu  9351 non-null   int64
 16  Price range           9351 non-null   int64
 17  Aggregate rating      9351 non-null   float64
 18  Rating color          9351 non-null   object
 19  Rating text           9351 non-null   object
 20  Votes                 9351 non-null   int64
 21  Price_Range           9351 non-null   object
dtypes: float64(3), int64(9), object(10)
memory usage: 1.6+ MB

In [119]:
ZomatoData['Aggregate rating'].value_counts()

0.0    2138
3.1     511
3.2     511
3.4     482
3.3     474
3.0     465
3.5     453
3.6     415
2.9     381
3.7     371
3.8     352
2.8     315
3.9     311
4.2     283
4.1     277
4.3     265
2.7     250
4.0     237
2.6     190
4.4     151
2.5     109
4.5     109
2.4      82
4.6      57
2.3      48
4.7      26
2.2      26
4.9      25
2.1      15
4.8      12
2.0       7
1.9       2
1.8       1
Name: Aggregate rating, dtype: int64